services:
  tempo:
    image: grafana/tempo:2.8.2
    container_name: tempo
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
    restart: unless-stopped
    networks:
      - primecart-nw

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo
    restart: unless-stopped
    networks:
      - primecart-nw

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - primecart-nw

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - tempo
      - prometheus
    restart: unless-stopped
    networks:
      - primecart-nw

volumes:
  tempo-data:
  prometheus-data:
  grafana-data:

networks:
  primecart-nw:
    external: true