apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: primecart-ui
  namespace: primecart-app
spec:
  ingressClassName: nginx
  rules:
    - host: primecart.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: primecart-ui
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  namespace: primecart-app
spec:
  ingressClassName: nginx
  rules:
    - host: api.primecart.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: primecart-infra
spec:
  ingressClassName: nginx
  rules:
    - host: auth.primecart.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: primecart-observe
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.primecart.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-grafana
                port:
                  name: http-web