apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications
  - platform

labels:
  - pairs:
      app.kubernetes.io/environment: prod
    includeSelectors: false
    includeTemplates: true