receivers:
  file_log/customer:
    include:
      - /var/log/primecart/customer-service.json
    start_at: end
    include_file_path: true
    include_file_name: true
    poll_interval: 200ms
    storage: file_storage
    operators:
      - type: json_parser
        parse_from: body

  file_log/product:
    include:
      - /var/log/primecart/product-service.json
    start_at: end
    include_file_path: true
    include_file_name: true
    poll_interval: 200ms
    storage: file_storage
    operators:
      - type: json_parser
        parse_from: body


processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 256
    spike_limit_mib: 64

  resource/customer:
    attributes:
      - key: service.name
        value: customer-service
        action: upsert
      - key: deployment.environment
        value: local
        action: upsert

  resource/product:
    attributes:
      - key: service.name
        value: product-service
        action: upsert
      - key: deployment.environment
        value: local
        action: upsert

  batch:
    timeout: 1s
    send_batch_size: 32

exporters:
  splunk_hec/customer:
    token: 8c953faa-8cac-4c32-8c9d-primecart-hec
    endpoint: http://primecart-splunk:8088/services/collector

    source: customer-service
    sourcetype: primecart:json
    index: main

    tls:
      insecure: true

    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 5m

    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 1000
      storage: file_storage

  splunk_hec/product:
    token: ${env:SPLUNK_HEC_TOKEN}
    endpoint: http://primecart-splunk:8088/services/collector

    source: product-service
    sourcetype: primecart:json
    index: main

    tls:
      insecure: true

    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 5m

    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 1000
      storage: file_storage

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

  file_storage:
    directory: /var/lib/otelcol

service:
  extensions:
    - health_check
    - file_storage

  telemetry:
    logs:
      level: info

  pipelines:
    logs/customer:
      receivers:
        - file_log/customer
      processors:
        - memory_limiter
        - resource/customer
        - batch
      exporters:
        - splunk_hec/customer

    logs/product:
      receivers:
        - file_log/product
      processors:
        - memory_limiter
        - resource/product
        - batch
      exporters:
        - splunk_hec/product