server:
  ssl:
    enabled: false

  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: api-gateway

  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}

  cloud:
    config:
      label: ${CONFIG_GIT_DEFAULT_LABEL:main}