server:
  ssl:
    enabled: true
    certificate: file:/Users/dadaramjadhav/primecart/infra/tls/localhost-cert.pem
    certificate-private-key: file:/Users/dadaramjadhav/primecart/infra/tls/localhost-key.pem

  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: api-gateway

  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      label: main