package com.primecart.entity;

public enum OrderStatus {

    PENDING, INVENTORY_RESERVED, INVENTORY_REJECTED, PAYMENT_PENDING, CONFIRMED, PAYMENT_FAILED, CANCELLED,

    CREATED, PAID, SHIPPED, DELIVERED
}