apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/applications/api-gateway
  - ../../../base/applications/cart-service
  - ../../../base/applications/customer-service
  - ../../../base/applications/inventory-service
  - ../../../base/applications/order-service
  - ../../../base/applications/payment-service
  - ../../../base/applications/product-service
  - ../../../base/applications/primecart-ui

images:
  - name: dadaramjadhav/primecart-api-gateway
    newTag: 8df8b612b2952f693e331f56202f9f9ae3d5a6f1

  - name: dadaramjadhav/primecart-cart-service
    newTag: 8df8b612b2952f693e331f56202f9f9ae3d5a6f1

  - name: dadaramjadhav/primecart-customer-service
    newTag: 8df8b612b2952f693e331f56202f9f9ae3d5a6f1

  - name: dadaramjadhav/primecart-inventory-service
    newTag: 8df8b612b2952f693e331f56202f9f9ae3d5a6f1

  - name: dadaramjadhav/primecart-order-service
    newTag: 8df8b612b2952f693e331f56202f9f9ae3d5a6f1

  - name: dadaramjadhav/primecart-payment-service
    newTag: 8df8b612b2952f693e331f56202f9f9ae3d5a6f1

  - name: dadaramjadhav/primecart-product-service
    newTag: 8df8b612b2952f693e331f56202f9f9ae3d5a6f1

  - name: dadaramjadhav/primecart-ui
    newTag: d91090c4e943275860d3ca9644aaf5bbea903ed4