server:
  port: 8085

primecart:
  security:
    jwt:
      audience: primecart-api

spring:
  application:
    name: payment-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123

    publisher-confirm-type: correlated
    publisher-returns: true

    template:
      mandatory: true

    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        concurrency: 2
        max-concurrency: 5
        prefetch: 10

        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 2
          max-interval: 10000ms
  boot:
    admin:
      client:
        url: http://localhost:9191
        username: admin
        password: 123

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Admin@12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/primecart

      client:
        registration:
          payment-service-client:
            provider: keycloak
            client-id: primecart-payment-service
            client-secret: 0tMEQ0grjTGL16CdWGINY3wXezPg8zz2
            authorization-grant-type: client_credentials

        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/primecart/protocol/openid-connect/token

  cloud:
    openfeign:
      micrometer:
        enabled: true

management:
  endpoint:
    health:
      show-details: when-authorized

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches

  tracing:
    enabled: true
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

info:
  app:
    name: Payment Service
    description: PrimeCart Payment Microservice
    version: 1.0.0

logging:
  level:
    root: INFO
    com.primecart: DEBUG
    org.springframework.web: INFO
    com.primecart.config.OrderClientCredentialsFeignConfig: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.springframework.security: DEBUG