server:
  port: 8081

spring:
  application:
    name: product-service

  boot:
    admin:
      client:
        url: http://localhost:9191

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 2s
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: Admin@12345

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/primecart

management:
  endpoints:
    web:
      exposure:
        include: "*"
  #        include: health,info,metrics,prometheus,caches

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

info:
  app:
    name: Product Service
    description: PrimeCart Product Microservice
    version: 1.0.0

logging:
  level:
    org.springframework.security: DEBUG

#retry config
resilience4j:
  retry:
    instances:
      productRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.io.IOException
#          - feign.RetryableException
