server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: inventory-service
  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      label: main
