server:
  port: 8084


spring:
  application:
    name: inventory-service


  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Admin@12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
  #    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/primecart

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    enabled: true
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

info:
  app:
    name: Cart Service
    description: PrimeCart Cart Microservice
    version: 1.0.0

logging:
  level:
    org.springframework.security: INFO
#    org.hibernate.SQL: DEBUG