server:
  port: 8083

primecart:
  security:
    jwt:
      audience: primecart-api

spring:
  application:
    name: cart-service

  boot:
    admin:
      client:
        url: http://localhost:9191
        username: admin
        password: 123
  cloud:
    openfeign:
      micrometer:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/cart_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Admin@12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/primecart

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches
  endpoint:
    health:
      show-details: when-authorized

  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
info:
  app:
    name: Cart Service
    description: PrimeCart Cart Microservice
    version: 1.0.0

logging:
  level:
    org.springframework.security: INFO
#    org.hibernate.SQL: DEBUG