server:
  port: 9191

spring:
  application:
    name: spring-boot-admin-server

  security:
    user:
      name: admin
      password: ${SBA_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized