services:

  logstash:
    image: docker.elastic.co/logstash/logstash:8.18.3
    container_name: logstash

    environment:
      SPLUNK_HEC_TOKEN: "8c953faa-8cac-4c32-8c9d-primecart-hec"
    ports:
      - "5001:5000"

    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

    networks:
      - primecart-nw

    restart: unless-stopped

networks:
  primecart-nw:
    external: true