input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {

}

output {
   http {
      url => "http://primecart-splunk:8088/services/collector/raw?index=main&sourcetype=primecart:json&source=%{[service]}"
      http_method => "post"
      format => "json"
      content_type => "application/json"

      headers => {
        "Authorization" => "Splunk 8c953faa-8cac-4c32-8c9d-primecart-hec"
      }

      automatic_retries => 2
      retry_failed => true
    }
}