server:
  port: 8888

  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: config-server

  boot:
    admin:
      client:
        url: ${SBA_URL:http://localhost:9191}
        username: ${SBA_USERNAME:admin}
        password: ${SBA_PASSWORD}

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/dadaramjadhav/primecart-config.git}
          username: ${CONFIG_GIT_USERNAME:dadaramjadhav}
          password: ${GITHUB_ACCESS_TOKEN}
          default-label: ${CONFIG_GIT_DEFAULT_LABEL:main}
          clone-on-start: true
          timeout: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always