name: Cart Service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "cart-service/**"
      - ".github/workflows/cart-service-ci.yml"
      - ".github/workflows/reusable-java-service-ci.yml"

  push:
    branches:
      - main
    paths:
      - "cart-service/**"
      - ".github/workflows/cart-service-ci.yml"
      - ".github/workflows/reusable-java-service-ci.yml"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: cart-service-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cart-service:
    name: Cart Service pipeline
    uses: ./.github/workflows/reusable-java-service-ci.yml

    with:
      service_directory: cart-service
      service_name: cart-service
      dockerhub_image_name: primecart-cart-service
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      sonar_project_key: ${{ vars.SONAR_CART_SERVICE_PROJECT_KEY }}
      sonar_organization: ${{ vars.SONAR_ORGANIZATION }}
      java_version: "17"

    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}